(define (main)
  (let* ((n (read))
         (m (make-vector n n 0))
         (count 0))
    (for ((i 0) (i < n))
      (for ((j 0) (j < n))
        (set! m i j (read))
        (if (= m i j 1)
            (set! count (+ count 1)))))
    (displayln count)))